version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip -o terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - echo "Terraform installed."

  pre_build:
    commands:
      - echo "Initializing Terraform backend..."
      - terraform init \
          -backend-config="bucket=sanju-terraform-state-eks" \
          -backend-config="key=eks-rds-fullstack/terraform.tfstate" \
          -backend-config="region=us-east-1" \
          -backend-config="dynamodb_table=terraform-lock-table" \
          -backend-config="encrypt=true"

  build:
    commands:
      - echo "Validating Terraform code..."
      - terraform validate
      - echo "Running Terraform plan..."
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform plan..."
      - terraform apply -auto-approve tfplan
      - echo "Terraform deployment completed."
